# SPDX-FileCopyrightText: 2020 Diego Elio Pettenò
#
# SPDX-License-Identifier: Unlicense

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: '^(tests/.*\.exp|tests/cmdline/.*|tests/.*/data/.*|ports/raspberrypi/sdk|lib/tinyusb)'
    -   id: trailing-whitespace
        exclude: '^(tests/.*\.exp|tests/cmdline/.*|tests/.*/data/.*|lib/mbedtls_errors/generate_errors.diff|ports/raspberrypi/sdk|lib/tinyusb)'
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
    -   id: codespell
        args: [-w]
        exclude: |
          (?x)^(
            locale/|
            lib/|
            tests/unicode/data/utf-8_invalid.txt|
            tests/extmod/data/qr.pgm|
            tests/basics/bytearray_byte_operations.py|
            ports/raspberrypi/sdk
          )
-   repo: local
    hooks:
    -   id: translations
        name: Translations
        entry: sh -c "if ! make check-translate; then make translate; fi"
        types: [c]
        pass_filenames: false
        language: system
    -   id: formatting
        name: Formatting
        entry: python3 tools/codeformat.py
        types_or: [c, python]
        language: system
        exclude: |
          (?x)^(
            lib/tinyusb|
            ports/raspberrypi/sdk
          )
